ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "barcode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "vendorId" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "vendorName" TEXT;
