export const mapBillToFrontend = (bill: any) => ({
  id: bill.id,
  billNumber: bill.billNumber,
  billType: bill.billType || 'CREDIT',
  vendorId: bill.vendorId,
  vendorName: bill.vendor?.company || bill.vendor?.name || '',
  vendorEmail: bill.vendor?.email || '',
  items: (bill.items || []).map((item: any) => ({
    id: item.id,
    productId: item.productId || '',
    productName: item.productName || item.product?.name || '',
    productSku: item.productSku || item.product?.sku || item.productId || '',
    serialNumber: item.serialNumber || null,
    serialNumbers: Array.isArray(item.serialNumbers)
      ? item.serialNumbers
      : (item.serialNumbers ? JSON.parse(JSON.stringify(item.serialNumbers)) : []),
    quantity: Number(item.quantity || 0),
    unitPrice: Number(item.unitPrice || 0),
    taxRate: Number(item.taxRate || 0),
    discount: Number(item.discount || 0),
    total: Number(item.total || 0),
    product: item.product ? { id: item.product.id, sku: item.product.sku, name: item.product.name } : undefined,
  })),
  subtotal: Number(bill.subtotal || 0),
  taxAmount: Number(bill.taxAmount || 0),
  discountAmount: Number(bill.discountAmount || 0),
  amount: Number(bill.amount || 0),
  paidAmount: Number(bill.paidAmount ?? 0),
  balanceAmount: Number(bill.balanceAmount ?? bill.amount ?? 0),
  status: bill.status || 'unpaid',
  date: bill.date,
  dueDate: bill.dueDate,
  paidAt: bill.paidAt,
  notes: bill.notes || '',
  createdAt: bill.createdAt,
  updatedAt: bill.updatedAt,
  createdBy: bill.createdBy || '',
});
